### ISSUE TITLE
npm build issues

### ISSUE THREAD

**Issue by msangapu-msft** [craigshoemaker/livewire#46]
2020-10-21T11:40:24.8372647Z ##[section]Starting: npm install and build
2020-10-21T11:40:24.8378648Z ==============================================================================
2020-10-21T11:40:24.8379245Z Task         : Command line
2020-10-21T11:40:24.8379688Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-10-21T11:40:24.8380114Z Version      : 2.176.1
2020-10-21T11:40:24.8380441Z Author       : Microsoft Corporation
2020-10-21T11:40:24.8380880Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-10-21T11:40:24.8381396Z ==============================================================================
2020-10-21T11:40:25.8291801Z Generating script.
2020-10-21T11:40:25.8298507Z ========================== Starting Command Output ===========================
2020-10-21T11:40:25.8316217Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/670c2470-e861-4a77-9f3b-639fb8fdcdb8.sh
2020-10-21T11:40:51.8185852Z 
2020-10-21T11:40:51.8188551Z > yorkie@2.0.0 install /home/vsts/work/1/s/ui/node_modules/yorkie
2020-10-21T11:40:51.8189814Z > node bin/install.js
2020-10-21T11:40:51.8190714Z 
2020-10-21T11:40:51.8969854Z CI detected, skipping Git hooks installation
2020-10-21T11:40:51.9672763Z 
2020-10-21T11:40:51.9675705Z > core-js@3.6.5 postinstall /home/vsts/work/1/s/ui/node_modules/core-js
2020-10-21T11:40:51.9677181Z > node -e "try{require('./postinstall')}catch(e){}"
2020-10-21T11:40:51.9678020Z 
2020-10-21T11:40:52.0463028Z [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2020-10-21T11:40:52.0463855Z 
2020-10-21T11:40:52.0464616Z [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
2020-10-21T11:40:52.0465447Z [96m>[94m https://opencollective.com/core-js [0m
2020-10-21T11:40:52.0466056Z [96m>[94m https://www.patreon.com/zloirock [0m
2020-10-21T11:40:52.0466364Z 
2020-10-21T11:40:52.0467025Z [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2020-10-21T11:40:52.0467456Z 
2020-10-21T11:40:52.0656623Z 
2020-10-21T11:40:52.0657654Z > ejs@2.7.4 postinstall /home/vsts/work/1/s/ui/node_modules/ejs
2020-10-21T11:40:52.0658257Z > node ./postinstall.js
2020-10-21T11:40:52.0658631Z 
2020-10-21T11:40:52.1479660Z Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
2020-10-21T11:40:52.1481245Z 
2020-10-21T11:40:53.1991726Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
2020-10-21T11:40:53.1992976Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-10-21T11:40:53.2018333Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
2020-10-21T11:40:53.2020281Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-10-21T11:40:53.2051353Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
2020-10-21T11:40:53.2053476Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-10-21T11:40:53.2059224Z 
2020-10-21T11:40:53.2096353Z added 1320 packages from 882 contributors and audited 1326 packages in 18.865s
2020-10-21T11:40:53.9252970Z 
2020-10-21T11:40:53.9254437Z 49 packages are looking for funding
2020-10-21T11:40:53.9255226Z   run `npm fund` for details
2020-10-21T11:40:53.9255785Z 
2020-10-21T11:40:53.9263565Z found 0 vulnerabilities
2020-10-21T11:40:53.9263887Z 
2020-10-21T11:40:54.4586554Z 
2020-10-21T11:40:54.4588056Z > livewire-ui@0.1.0 build /home/vsts/work/1/s/ui
2020-10-21T11:40:54.4588737Z > npm run build-vue & npm run build-css
2020-10-21T11:40:54.4589354Z 
2020-10-21T11:40:54.7326851Z 
2020-10-21T11:40:54.7328472Z > livewire-ui@0.1.0 build-vue /home/vsts/work/1/s/ui
2020-10-21T11:40:54.7331380Z > vue-cli-service build
2020-10-21T11:40:54.7332161Z 
2020-10-21T11:40:54.7432530Z 
2020-10-21T11:40:54.7434256Z > livewire-ui@0.1.0 build-css /home/vsts/work/1/s/ui
2020-10-21T11:40:54.7435242Z > postcss src/assets/app.css -o dist/css/app.css
2020-10-21T11:40:54.7435834Z 
2020-10-21T11:40:55.4077700Z 
2020-10-21T11:40:55.4091794Z -  Building for production...
2020-10-21T11:41:00.2053067Z   
2020-10-21T11:41:00.2060020Z    âš ï¸  Tailwind is not purging unused styles because no template paths have been provided.
2020-10-21T11:41:00.2061461Z       If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
2020-10-21T11:41:00.2062466Z       removing unused styles, set `purge: false` in your Tailwind config file to silence
2020-10-21T11:41:00.2063224Z       this warning.
2020-10-21T11:41:00.2063509Z    
2020-10-21T11:41:00.2064439Z       https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
2020-10-21T11:41:03.2549334Z (node:2902) UnhandledPromiseRejectionWarning: Error: Expected an attribute.
2020-10-21T11:41:03.2551084Z     at Root._error (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:160:16)
2020-10-21T11:41:03.2552015Z     at Root.error (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
2020-10-21T11:41:03.2552940Z     at Parser.error (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:726:21)
2020-10-21T11:41:03.2553884Z     at Parser.expected (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:1113:19)
2020-10-21T11:41:03.2554811Z     at Parser.attribute (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:188:19)
2020-10-21T11:41:03.2555723Z     at Parser.parse (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:1053:14)
2020-10-21T11:41:03.2556636Z     at Parser.loop (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:1023:12)
2020-10-21T11:41:03.2557526Z     at new Parser (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/parser.js:150:10)
2020-10-21T11:41:03.2558436Z     at Processor._root (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/processor.js:55:18)
2020-10-21T11:41:03.2559352Z     at Processor._runSync (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/processor.js:102:21)
2020-10-21T11:41:03.2560300Z     at Processor.processSync (/home/vsts/work/1/s/ui/node_modules/postcss-selector-parser/dist/processor.js:199:23)
2020-10-21T11:41:03.2560962Z     at x.evaluateRule (/home/vsts/work/1/s/ui/node_modules/purgecss/lib/purgecss.js:1:6211)
2020-10-21T11:41:03.2561537Z     at e.walk.e (/home/vsts/work/1/s/ui/node_modules/purgecss/lib/purgecss.js:1:8700)
2020-10-21T11:41:03.2562444Z     at /home/vsts/work/1/s/ui/node_modules/postcss/lib/container.js:135:18
2020-10-21T11:41:03.2563018Z     at Root.each (/home/vsts/work/1/s/ui/node_modules/postcss/lib/container.js:101:16)
2020-10-21T11:41:03.2563588Z     at Root.walk (/home/vsts/work/1/s/ui/node_modules/postcss/lib/container.js:131:17)
2020-10-21T11:41:03.2564587Z (node:2902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-10-21T11:41:03.2566184Z (node:2902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-10-21T11:41:07.1805390Z  ERROR  Error: CSS minification error: Expected an attribute.. File: css/app.5e911f99.css
2020-10-21T11:41:07.1807640Z Error: CSS minification error: Expected an attribute.. File: css/app.5e911f99.css
2020-10-21T11:41:07.1810134Z     at /home/vsts/work/1/s/ui/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21
2020-10-21T11:41:07.1812318Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-21T11:41:07.1964513Z npm ERR! code ELIFECYCLE
2020-10-21T11:41:07.1966487Z npm ERR! errno 1
2020-10-21T11:41:07.1987465Z npm ERR! livewire-ui@0.1.0 build-vue: `vue-cli-service build`
2020-10-21T11:41:07.1988488Z npm ERR! Exit status 1
2020-10-21T11:41:07.1989330Z npm ERR! 
2020-10-21T11:41:07.1990506Z npm ERR! Failed at the livewire-ui@0.1.0 build-vue script.
2020-10-21T11:41:07.1991055Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-10-21T11:41:07.3199438Z 
2020-10-21T11:41:07.3201308Z npm ERR! A complete log of this run can be found in:
2020-10-21T11:41:07.3202557Z npm ERR!     /home/vsts/.npm/_logs/2020-10-21T11_41_07_199Z-debug.log
2020-10-21T11:41:07.3243635Z 
2020-10-21T11:41:07.3297126Z ##[section]Finishing: npm install and build

**Comment by craigshoemaker** [comment]
Closed by e496feaeb19bface616680c0807433251224b137
